config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # ///////////////////////////////////////////////////////////////////////////////////////////////////

  # list routes
  # A user can see all the lists
  # A user can see a specific list
  # A user can create a new list
  resources :lists, only: [:show, :new, :create, :destroy] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy

  # Bookmark routes
  # A user can add a new bookmark (movie/list pair) to an existing list
  # A user can delete a bookmark from a list. How can we make a delete link again?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # do not understand this
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.required(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, prompt: "Select a movie" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class='navbar-rutger'>
      <div class='navbar-left'>
        <i class="fa-solid fa-film fa-3x navbar-brand navbar-logo"></i>
      </div>
      <div class="navbar-right">
        <%= link_to 'my lists', root_path, class: "btn btn-outline-primary", style: "margin-right: 10px;" %>
        <%= link_to 'create a new list', new_list_path, class: "btn btn-outline-primary" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner cinema-seats">
<h1>your lists</h1>
</div>


<div class="container">
<% @lists.each do |l| %>
  <div class="card" style="width: 18rem;">
    <%= image_tag "Big_lebowski.jpg", alt: "big lebowski", class: "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title"><%= l.name %></h5>
      <p class="card-text">empty info for now</p>
      <%= link_to 'list details', list_path(l.id), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="banner cinema-seats">
  <h1><%= @list.name %></h1>
</div>

<div class="container">
  <% @list.bookmarks.each do |b| %>
    <div class="card" style="width: 18rem;">
    <%= image_tag b.movie.poster_url, alt: "big lebowski", class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= b.movie.title %></h5>
        <%# <%= b.movie.rating %>
        <p class="card-text"><%= b.movie.overview %></p>
        <h5><em>"<%= b.comment %>"</em></h4>
      </div>
    </div>
  <% end %>
</div>
<hr>
<div class="container">
  <%= link_to 'Create a bookmark', new_list_bookmark_path(@list), class: "btn btn-primary" %>
  <%= link_to "Delete this list",
    list_path(@list),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
    class: "btn btn-primary"
  %>
</div>